import UIKit

extension Crayon {
    
    // STRONG
    static let cantaloupe = Crayon(backgroundColor: .cantaloupe, textColor: .white, sectionColor: .cantaloupe, name: "cantaloupe", scheme: .strong)
    static let honeydew =   Crayon(backgroundColor: .honeydew, textColor: .tungsten, sectionColor: .honeydew, name: "honeydew", scheme: .strong)
    static let spindrift =  Crayon(backgroundColor: .spindrift, textColor: .tungsten, sectionColor: .spindrift, name: "spindrift", scheme: .strong)
    static let sky =        Crayon(backgroundColor: .sky, textColor: .white, sectionColor: .sky, name: "sky", scheme: .strong)
    static let lavender =   Crayon(backgroundColor: .lavender, textColor: .white, sectionColor: .lavender, name: "lavender", scheme: .strong)
    static let carnation =  Crayon(backgroundColor: .carnation, textColor: .white, sectionColor: .carnation, name: "carnation", scheme: .strong)
    static let licorice =   Crayon(backgroundColor: .licorice, textColor: .white, sectionColor: .licorice, name: "licorice", scheme: .strong)
    static let snow =       Crayon(backgroundColor: .snow, textColor: .tungsten, sectionColor: .snow, name: "snow", scheme: .strong)
    static let salmon =     Crayon(backgroundColor: .salmon, textColor: .white, sectionColor: .salmon, name: "salmon", scheme: .strong)
    static let banana =     Crayon(backgroundColor: .banana, textColor: .tungsten, sectionColor: .banana, name: "banana", scheme: .strong)
    static let flora =      Crayon(backgroundColor: .flora, textColor: .tungsten, sectionColor: .flora, name: "flora", scheme: .strong)
    static let ice =        Crayon(backgroundColor: .ice, textColor: .tungsten, sectionColor: .ice, name: "ice", scheme: .strong)
    static let orchid =     Crayon(backgroundColor: .orchid, textColor: .white, sectionColor: .orchid, name: "orchid", scheme: .strong)
    static let bubblegum =  Crayon(backgroundColor: .bubblegum, textColor: .white, sectionColor: .bubblegum, name: "bubblegum", scheme: .strong)
    static let lead =       Crayon(backgroundColor: .lead, textColor: .white, sectionColor: .lead, name: "lead", scheme: .strong)
    static let mercury =    Crayon(backgroundColor: .mercury, textColor: .tungsten, sectionColor: .mercury, name: "mercury", scheme: .strong)
    static let tangerine =  Crayon(backgroundColor: .tangerine, textColor: .white, sectionColor: .tangerine, name: "tangerine", scheme: .strong)
    static let lime =       Crayon(backgroundColor: .lime, textColor: .tungsten, sectionColor: .lime, name: "lime", scheme: .strong)
    static let seaFoam =    Crayon(backgroundColor: .seaFoam, textColor: .tungsten, sectionColor: .seaFoam, name: "Sea Foam", scheme: .strong)
    static let aqua =       Crayon(backgroundColor: .aqua, textColor: .white, sectionColor: .aqua, name: "aqua", scheme: .strong)
    static let grape =      Crayon(backgroundColor: .grape, textColor: .white, sectionColor: .grape, name: "grape", scheme: .strong)
    static let strawberry = Crayon(backgroundColor: .strawberry, textColor: .white, sectionColor: .strawberry, name: "strawberry", scheme: .strong)
    static let tungsten =   Crayon(backgroundColor: .tungsten, textColor: .white, sectionColor: .tungsten, name: "tungsten", scheme: .strong)
    static let silver =     Crayon(backgroundColor: .silver, textColor: .tungsten, sectionColor: .silver, name: "silver", scheme: .strong)
    static let maraschino = Crayon(backgroundColor: .maraschino, textColor: .white, sectionColor: .maraschino, name: "maraschino", scheme: .strong)
    static let lemon =      Crayon(backgroundColor: .lemon, textColor: .tungsten, sectionColor: .lemon, name: "lemon", scheme: .strong)
    static let spring =     Crayon(backgroundColor: .spring, textColor: .tungsten, sectionColor: .spring, name: "spring", scheme: .strong)
    static let turquoise =  Crayon(backgroundColor: .turquoise, textColor: .tungsten, sectionColor: .turquoise, name: "turquoise", scheme: .strong)
    static let blueberry =  Crayon(backgroundColor: .blueberry, textColor: .white, sectionColor: .blueberry, name: "blueberry", scheme: .strong)
    static let magenta =    Crayon(backgroundColor: .magenta, textColor: .white, sectionColor: .magenta, name: "magenta", scheme: .strong)
    static let iron =       Crayon(backgroundColor: .iron, textColor: .white, sectionColor: .iron, name: "iron", scheme: .strong)
    static let magnesium =  Crayon(backgroundColor: .magnesium, textColor: .white, sectionColor: .magnesium, name: "magnesium", scheme: .strong)
    static let mocha =      Crayon(backgroundColor: .mocha, textColor: .white, sectionColor: .mocha, name: "mocha", scheme: .strong)
    static let fern =       Crayon(backgroundColor: .fern, textColor: .white, sectionColor: .fern, name: "fern", scheme: .strong)
    static let moss =       Crayon(backgroundColor: .moss, textColor: .white, sectionColor: .moss, name: "moss", scheme: .strong)
    static let ocean =      Crayon(backgroundColor: .ocean, textColor: .white, sectionColor: .ocean, name: "ocean", scheme: .strong)
    static let eggplant =   Crayon(backgroundColor: .eggplant, textColor: .white, sectionColor: .eggplant, name: "eggplant", scheme: .strong)
    static let maroon =     Crayon(backgroundColor: .maroon, textColor: .white, sectionColor: .maroon, name: "maroon", scheme: .strong)
    static let steel =      Crayon(backgroundColor: .steel, textColor: .white, sectionColor: .steel, name: "steel", scheme: .strong)
    static let aluminum =   Crayon(backgroundColor: .aluminum, textColor: .white, sectionColor: .aluminum, name: "aluminum", scheme: .strong)
    static let cayenne =    Crayon(backgroundColor: .cayenne, textColor: .white, sectionColor: .cayenne, name: "cayenne", scheme: .strong)
    static let aspargus =   Crayon(backgroundColor: .aspargus, textColor: .white, sectionColor: .aspargus, name: "aspargus", scheme: .strong)
    static let clover =     Crayon(backgroundColor: .clover, textColor: .white, sectionColor: .clover, name: "clover", scheme: .strong)
    static let teal =       Crayon(backgroundColor: .teal, textColor: .white, sectionColor: .teal, name: "teal", scheme: .strong)
    static let midnight =   Crayon(backgroundColor: .midnight, textColor: .white, sectionColor: .midnight, name: "midnight", scheme: .strong)
    static let plum =       Crayon(backgroundColor: .plum, textColor: .white, sectionColor: .plum, name: "plum", scheme: .strong)
    static let tin =        Crayon(backgroundColor: .tin, textColor: .white, sectionColor: .tin, name: "tin", scheme: .strong)
    static let nickel =     Crayon(backgroundColor: .nickel, textColor: .white, sectionColor: .nickel, name: "nickel", scheme: .strong)
}
